import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val org_jetbrains_kotlinx_kotlinx_coroutines: String = "1.4.2"

    const val com_squareup_retrofit2: String = "2.7.2" // available: "2.9.0"

    const val androidx_databinding: String = "4.1.1"

    const val org_jetbrains_kotlin: String = "1.4.21"

    const val androidx_navigation: String = "2.3.2"

    const val androidx_lifecycle: String = "2.2.0"

    const val com_android_tools_build_gradle: String = "4.2.1"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    const val logging_interceptor: String = "4.9.0"

    const val legacy_support_v4: String = "1.0.0"

    const val constraintlayout: String = "2.0.4"

    const val viewpager2: String = "1.0.0"

    const val appcompat: String = "1.2.0"

    const val material: String = "1.2.1"

    const val aapt2: String = "4.1.1-6503028"

    const val coil: String = "1.1.0"

    const val admob: String = "20.1.0"

    const val gnrAdLibs: String = "1.0.0"

    const val navigation_saf_args = "2.3.2"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
        id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
